import pyodbc
import pandas as pd
from typing import List, Dict, Any, Optional
from config import get_pyodbc_connection_string, settings
import logging

logger = logging.getLogger(__name__)


class DatabaseManager:
    def __init__(self):
        self.connection_string = get_pyodbc_connection_string()

    def get_connection(self):
        """Get database connection"""
        try:
            return pyodbc.connect(self.connection_string)
        except Exception as e:
            logger.error(f"Database connection error: {e}")
            raise

    def execute_query(
        self, query: str, params: tuple = None, fetch_size: int = 10000
    ) -> List[Dict[str, Any]]:
        """Execute query and return results as list of dictionaries"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()

                # Set fetch size for large datasets
                cursor.arraysize = fetch_size

                if params:
                    cursor.execute(query, params)
                else:
                    cursor.execute(query)

                # Get column names
                columns = [column[0] for column in cursor.description]

                # Fetch results in chunks for memory efficiency
                results = []
                while True:
                    rows = cursor.fetchmany(fetch_size)
                    if not rows:
                        break

                    for row in rows:
                        results.append(dict(zip(columns, row)))

                return results

        except Exception as e:
            logger.error(f"Query execution error: {e}")
            raise

    def execute_query_pandas(self, query: str, params: tuple = None) -> pd.DataFrame:
        """Execute query and return pandas DataFrame for large datasets"""
        try:
            with self.get_connection() as conn:
                if params:
                    df = pd.read_sql(query, conn, params=params)
                else:
                    df = pd.read_sql(query, conn)
                return df
        except Exception as e:
            logger.error(f"Pandas query execution error: {e}")
            raise

    def execute_non_query(self, query: str, params: tuple = None) -> int:
        """Execute non-query (INSERT, UPDATE, DELETE) and return affected rows"""
        try:
            with self.get_connection() as conn:
                cursor = conn.cursor()
                if params:
                    cursor.execute(query, params)
                else:
                    cursor.execute(query)

                affected_rows = cursor.rowcount
                conn.commit()
                return affected_rows

        except Exception as e:
            logger.error(f"Non-query execution error: {e}")
            raise


# Global database manager instance
db_manager = DatabaseManager()


# Initialize database with required tables for the application
def init_database():
    """Initialize database with required tables for dynamic menus, queries, etc."""

    # Create users table for authentication
    create_users_table = """
    CREATE TABLE IF NOT EXISTS app_users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(50) UNIQUE NOT NULL,
        email VARCHAR2(100) UNIQUE NOT NULL,
        password_hash VARCHAR2(255) NOT NULL,
        is_active NUMBER(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """

    # Create menu items table for dynamic sidebar
    create_menu_items_table = """
    CREATE TABLE IF NOT EXISTS app_menu_items (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        type VARCHAR2(20) NOT NULL, -- 'dashboard' or 'report'
        icon VARCHAR2(50),
        parent_id NUMBER,
        sort_order NUMBER DEFAULT 0,
        is_active NUMBER(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (parent_id) REFERENCES app_menu_items(id)
    )
    """

    # Create queries table for storing SQL queries
    create_queries_table = """
    CREATE TABLE IF NOT EXISTS app_queries (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(200) NOT NULL,
        description CLOB,
        sql_query CLOB NOT NULL,
        chart_type VARCHAR2(50), -- 'bar', 'pie', 'line', 'doughnut', etc.
        chart_config CLOB, -- JSON config for chart
        menu_item_id NUMBER,
        is_active NUMBER(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (menu_item_id) REFERENCES app_menu_items(id)
    )
    """

    # Create dashboard widgets table
    create_dashboard_widgets_table = """
    CREATE TABLE IF NOT EXISTS app_dashboard_widgets (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(200) NOT NULL,
        query_id NUMBER NOT NULL,
        position_x NUMBER DEFAULT 0,
        position_y NUMBER DEFAULT 0,
        width NUMBER DEFAULT 6,
        height NUMBER DEFAULT 4,
        is_active NUMBER(1) DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (query_id) REFERENCES app_queries(id)
    )
    """

    try:
        # Create tables (Note: Oracle doesn't support CREATE TABLE IF NOT EXISTS, so we'll handle errors)
        tables = [
            create_users_table,
            create_menu_items_table,
            create_queries_table,
            create_dashboard_widgets_table,
        ]

        for table_sql in tables:
            try:
                db_manager.execute_non_query(table_sql.replace("IF NOT EXISTS", ""))
            except Exception as e:
                if "name is already used" not in str(e).lower():
                    logger.warning(f"Table creation warning: {e}")

        # Insert default data
        insert_default_data()
        logger.info("Database initialized successfully")

    except Exception as e:
        logger.error(f"Database initialization error: {e}")
        raise


def insert_default_data():
    """Insert default menu items and sample queries"""

    # Insert default menu items
    default_menus = [
        ("Dashboard", "dashboard", "dashboard", None, 1),
        ("Reports", "report", "chart-bar", None, 2),
        ("Financial Overview", "report", "chart-line", 2, 1),
        ("Risk Analysis", "report", "shield-exclamation", 2, 2),
    ]

    for name, type_, icon, parent_id, sort_order in default_menus:
        try:
            db_manager.execute_non_query(
                "INSERT INTO app_menu_items (name, type, icon, parent_id, sort_order) VALUES (?, ?, ?, ?, ?)",
                (name, type_, icon, parent_id, sort_order),
            )
        except Exception:
            # Menu item already exists
            pass

    # Insert sample queries based on your data
    sample_queries = [
        (
            "Daily Financial Summary",
            "Summary of financial data by day",
            "SELECT day_of, ct_main, SUM(fcc_bkv) as total_bkv, SUM(fcc_ion) as total_ion, COUNT(*) as record_count FROM sample_bt GROUP BY day_of, ct_main ORDER BY day_of",
            "bar",
            '{"indexAxis": "x", "responsive": true}',
            1,  # Dashboard
        ),
        (
            "Main Category Distribution",
            "Distribution of records by main category",
            "SELECT ct_main, COUNT(*) as count FROM sample_bt WHERE ct_main IS NOT NULL GROUP BY ct_main ORDER BY count DESC",
            "pie",
            '{"responsive": true}',
            1,  # Dashboard
        ),
        (
            "Financial Values by Day",
            "BKV values trend over days",
            "SELECT day_of, SUM(fcc_bkv) as total_bkv FROM sample_bt GROUP BY day_of ORDER BY day_of",
            "line",
            '{"responsive": true, "scales": {"y": {"beginAtZero": true}}}',
            1,  # Dashboard
        ),
        (
            "Top Categories by Value",
            "Top performing categories by financial value",
            "SELECT ct_main, SUM(fcc_bkv) as total_value, SUM(fcc_ion) as total_ion FROM sample_bt WHERE ct_main IS NOT NULL GROUP BY ct_main ORDER BY total_value DESC FETCH FIRST 10 ROWS ONLY",
            "bar",
            '{"responsive": true, "indexAxis": "y"}',
            3,  # Financial Overview
        ),
    ]

    for name, desc, sql, chart_type, config, menu_id in sample_queries:
        try:
            db_manager.execute_non_query(
                "INSERT INTO app_queries (name, description, sql_query, chart_type, chart_config, menu_item_id) VALUES (?, ?, ?, ?, ?, ?)",
                (name, desc, sql, chart_type, config, menu_id),
            )
        except Exception:
            # Query already exists
            pass

    # Insert default dashboard widgets
    default_widgets = [
        ("Daily Summary", 1, 0, 0, 6, 4),
        ("Category Distribution", 2, 6, 0, 6, 4),
        ("Financial Trend", 3, 0, 4, 12, 4),
    ]

    for title, query_id, x, y, width, height in default_widgets:
        try:
            db_manager.execute_non_query(
                "INSERT INTO app_dashboard_widgets (title, query_id, position_x, position_y, width, height) VALUES (?, ?, ?, ?, ?, ?)",
                (title, query_id, x, y, width, height),
            )
        except Exception:
            # Widget already exists
            pass
